### ISSUE TITLE
mainUtil.dart 文件报错！

### ISSUE THREAD

**Issue by STGing** [ifgyong/flutter-example#1]
首先感谢这个示例，让我可以跟着学习flutter相关知识。
下载项目跑起来后报错，发现  在 mainUtil.dart  文件中的第48行报错

export 'package:fluttertest01/tips/async_and_async*.dart';

找到对应路径发现我这边的文件名是  async_and_async_.dart

修改为对应的文件名就好了。

**Comment by ifgyong** [comment]
一起学习哦

**Comment by ifgyong** [comment]
已修复  [1cb5490](https://github.com/ifgyong/flutter-example/commit/1cb54908e782f0169cfdd4f80b278dac538b6f95)
